version: "3.9"
services:
  db:
    image: postgres:16
    container_name: dse-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: docsearch
      POSTGRES_PASSWORD: docsearch
      POSTGRES_DB: docsearch
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U docsearch"]
      interval: 5s
      timeout: 5s
      retries: 10
volumes:
  pgdata:
