name: Deploy (Azure builds from source)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # DO NOT CHANGE the three lines below. Paste your existing values exactly.
      - name: Login to Azure
        uses: azure/login@v2
        with:
          # <— keep exactly as in your file
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_449C2286F0BB4D8C87DDDFD5D1F23817 }}
          # <— keep exactly as in your file
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_B973AA95BDDB4C49A6975085CA622576 }}
          # <— keep exactly as in your file
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_08053C01490A49349B359E2FE8EA0628 }}

      # Ship the repo as-is. Azure Oryx will install, build and start the app using your App Settings.
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: DocSearchEngine
          package: .
