name: Build & Deploy - DocSearchEngine

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  NODE_VERSION: 20

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      # Frontend
      - run: npm ci
        working-directory: frontend
      - run: npm run build
        working-directory: frontend

      # Backend
      - run: npm ci
        working-directory: backend
      - run: npm run build
        working-directory: backend

      # Copy UI into backend/dist/public
      - run: |
          mkdir -p backend/dist/public
          cp -r frontend/dist/* backend/dist/public/

      # Install runtime deps only in backend
      - run: |
          rm -rf backend/node_modules
          npm ci --omit=dev
        working-directory: backend

      # Zip backend only (faster deploy)
      - run: |
          cd backend
          zip -r ../backend.zip .

      - uses: actions/upload-artifact@v4
        with:
          name: backend-zip
          path: backend.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: backend-zip
          path: .

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: DocSearchEngine
          package: backend.zip
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISH_PROFILE }}
