name: deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: |
            package-lock.json
            backend/package-lock.json
            frontend/package-lock.json

      - name: Install (root workspaces)
        run: npm ci --workspaces --include-workspace-root

      - name: Build frontend
        run: npm --prefix frontend run build

      - name: Build backend (ts -> dist)
        run: npm --prefix backend run build

      - name: Place frontend assets where server serves them
        run: |
          mkdir -p backend/dist/public
          cp -R frontend/dist/* backend/dist/public/

      - name: Reinstall backend (prod only)
        run: |
          rm -rf backend/node_modules
          (cd backend && npm ci --omit=dev)

      - name: Zip backend
        run: |
          cd backend
          zip -r ../backend.zip package.json package-lock.json dist node_modules
          cd ..

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: docsearchengine-amd3dvf7hch0cnax
          package: backend.zip
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISH_PROFILE }}
