name: Deploy (prod)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      # Install all workspaces (root + backend + frontend) in one shot
      - name: Install deps (workspaces)
        run: npm ci --workspaces --include-workspace-root

      # Your root "build" orchestrates both: builds frontend & backend and
      # copies frontend/dist into backend/dist/public
      - name: Build app (frontend + backend)
        run: npm run build

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_449C2286F0BB4D8C87DDDFD5D1F23817 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_B973AA95BDDB4C49A6975085CA622576 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_08053C01490A49349B359E2FE8EA0628 }}

      # Deploy the repo; Azure will run Oryx build and then `npm start`
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'docsearchengine-amd3dvf7hch0cnax'  # your prod site
          package: .
