name: Deploy to Azure App Service

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install workspace dependencies
        run: npm ci --no-audit --no-fund

      - name: Build backend
        run: npm run build --workspace backend

      - name: Prepare frontend assets
        run: |
          rm -rf backend/dist/public
          mkdir -p backend/dist/public
          cp -R backend/public/. backend/dist/public/

      - name: Install backend production dependencies only
        run: npm install --omit=dev --no-audit --no-fund --prefix backend

      - name: Create deployment package
        run: |
          cd backend
          zip -r ../backend.zip . -x "*.git*"
          cd ..

      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_449C2286F0BB4D8C87DDDFD5D1F23817 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_B973AA95BDDB4C49A6975085CA622576 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_08053C01490A49349B359E2FE8EA0628 }}

      - name: Deploy to Azure Web App (prod)
        env:
          AZURE_WEBAPP_NAME: docsearchengine-amd3dvf7hch0cnax
          DEPLOY_PACKAGE: backend.zip
        run: |
          set -euo pipefail

          if [ ! -f "$DEPLOY_PACKAGE" ]; then
            echo "::error::Expected deployment package '$DEPLOY_PACKAGE' was not generated"
            exit 1
          fi

          RESOURCE_GROUP=$(az webapp list \
            --query "[?name=='${AZURE_WEBAPP_NAME}'].resourceGroup" \
            -o tsv)

          if [ -z "$RESOURCE_GROUP" ]; then
            echo "::error::Unable to determine resource group for app '$AZURE_WEBAPP_NAME'"
            exit 1
          fi

          az webapp deploy \
            --name "$AZURE_WEBAPP_NAME" \
            --resource-group "$RESOURCE_GROUP" \
            --src-path "$DEPLOY_PACKAGE" \
            --type zip
