name: Deploy (prod)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Build both workspaces. This repo already expects a root build that
      # compiles the backend and moves the frontend into backend/dist/public.
      - name: Build app (frontend + backend)
        run: |
          npm --prefix frontend install --include=dev --no-audit --no-fund
          npm --prefix frontend run build
          npm --prefix backend install --include=dev --no-audit --no-fund
          npm --prefix backend run build
          node -e "fs=require('fs');p='backend/dist/public';fs.mkdirSync(p,{recursive:true});fs.cpSync('frontend/dist',p,{recursive:true});"

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_449C2286F0BB4D8C87DDDFD5D1F23817 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_B973AA95BDDB4C49A6975085CA622576 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_08053C01490A49349B359E2FE8EA0628 }}

      # Ship the repo. Azure (Oryx) will run `npm install` + your build + `npm start`.
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'docsearchengine-amd3dvf7hch0cnax'  # << exact Prod app name
          package: .
