name: build

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install & Build (root orchestrates both)
        run: |
          npm ci
          npm run build

      - name: Deploy to Azure Web App
        if: github.event_name == 'push'
        uses: azure/webapps-deploy@v2
        with:
          app-name: DocSearchEngine
          package: .
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
