name: build

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install (backend)
        working-directory: backend
        run: npm ci

      - name: Build (backend)
        working-directory: backend
        run: npm run build

      # optional: upload dist as artifact for deploy
      - name: Upload artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: backend-dist
          path: backend/dist
