name: deploy (prod)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Install ONLY backend prod deps
      - name: Install backend (prod only)
        working-directory: backend
        run: npm install --omit=dev --no-audit --no-fund

      # Zip the backend folder so package.json is at the zip root
      - name: Zip backend
        run: |
          cd backend
          zip -r ../backend.zip package.json package-lock.json server.js public node_modules
          cd ..

      # Azure login via OIDC (keep your existing secrets)
      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_449C2286F0BB4D8C87DDDFD5D1F23817 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_B973AA95BDDB4C49A6975085CA622576 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_08053C01490A49349B359E2FE8EA0628 }}

      # Deploy JUST the backend zip
      - name: Deploy to Azure Web App (prod)
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'DocSearchEngine'
          package: backend.zip
