name: deploy (prod)

on:
  push:
    branches: [ "main" ]   # deploy straight from main
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Use Node 20 like your other app; no caching (prevents the lockfile error)
      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Install all deps (root + workspaces)
      - name: Install deps
        run: npm install

      # Build both frontend and backend using your root script
      - name: Build app
        run: npm run build

      # Package everything for deploy (same pattern as EncompassProxy)
      - uses: actions/upload-artifact@v4
        with:
          name: app
          path: .

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_A4F5A536F50143DAAC8FD0AFCE7AFCFC }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_A0FC6ACB513C478BB0A82DAE38B6FFEF }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_5D1AE4AA87F6461FB7BB2D2D9EC07C81 }}

      - name: Deploy to Azure Web App (prod)
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'DocSearchEngine'
          package: .
