name: Deploy (prod)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Build FE + BE the way your repo expects
      - name: Install (workspaces)
        run: npm ci --workspaces --include-workspace-root

      - name: Build frontend
        run: npm run -w frontend build

      - name: Build backend
        run: npm run -w backend build

      - name: Copy frontend into backend public
        run: |
          mkdir -p backend/dist/public
          cp -r frontend/dist/* backend/dist/public/

      # Create minimal backend bundle (prod deps only)
      - name: Reinstall backend (prod only) and zip
        run: |
          rm -rf backend/node_modules
          (cd backend && npm ci --omit=dev)
          (cd backend && zip -r ../backend.zip package.json package-lock.json dist node_modules)

      # ---- NEVER REMOVE THIS BLOCK ----
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_449C2286F0BB4D8C87DDDFD5D1F23817 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_B973AA95BDDB4C49A6975085CA622576 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_08053C01490A49349B359E2FE8EA0628 }}

      - name: Deploy to Azure Web App (prod)
        uses: azure/webapps-deploy@v3
        with:
          app-name: docsearchengine-amd3dvf7hch0cnax
          package: backend.zip
