name: deploy (prod)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dev deps for UI build
        run: npm ci

      - name: Build UI CSS (Tailwind)
        run: npm run build:ui

      # Install runtime deps inside backend (prod only) using its lockfile
      - name: Install backend (prod only)
        run: |
          cd backend
          npm ci --omit=dev

      # Zip the backend folder so package.json is at the zip root (like Proxy)
      - name: Zip backend
        run: |
          cd backend
          zip -r ../backend.zip .

      # ---- DO NOT REMOVE (Azure OIDC secrets) ----
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_449C2286F0BB4D8C87DDDFD5D1F23817 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_B973AA95BDDB4C49A6975085CA622576 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_08053C01490A49349B359E2FE8EA0628 }}

      - name: Deploy to Azure Web App (prod)
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'DocSearchEngine'      # App Service resource name (use the same value as Proxy uses)
          slot-name: 'Production'
          package: backend.zip
