name: deploy (prod)

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      # Install runtime deps inside backend using its lockfile
      - name: Install backend (prod only)
        run: |
          cd backend
          npm ci --omit=dev

      # Zip the backend folder so package.json is at the root of the zip,
      # along with node_modules and public assets (Proxy style)
      - name: Zip backend
        run: |
          cd backend
          zip -r ../backend.zip .

      # ---- DO NOT REMOVE ----  (keep your Azure login the way you prefer)
      - name: Login to Azure
        uses: azure/login@v2
        with:
          # EITHER OIDC (preferred) ...
          # client-id: ${{ secrets.AZURE_CLIENT_ID }}
          # tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          # subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          # OR publish profile (what you already have):
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISH_PROFILE }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: docsearchengine-amd3dvf7hch0cnax
          slot-name: Production
          package: backend.zip

      - name: Logout
        if: always()
        run: az logout
