name: deploy (prod)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

# REQUIRED for azure/login OIDC
permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: backend/package-lock.json

      - name: Install backend (prod only)
        working-directory: backend
        run: npm ci --omit=dev
        # If you ever hit CI lockfile errors again, use this instead:
        # run: npm ci --omit=dev || npm install --omit=dev --no-audit --no-fund

      - name: Zip backend
        run: |
          cd backend
          zip -r ../backend.zip package.json package-lock.json server.js public node_modules
          cd ..

      # ---- DO NOT REMOVE ----
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_449C2286F0BB4D8C87DDDFD5D1F23817 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_B973AA95BDDB4C49A6975085CA622576 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_08053C01490A49349B359E2FE8EA0628 }}

      - name: Deploy to Azure Web App (prod)
        uses: azure/webapps-deploy@v3
        with:
          app-name: docsearchengine-amd3dvf7hch0cnax
          package: backend.zip
