name: Deploy (prod)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  NODE_VERSION: '20'

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Use Node ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      # Install once for the whole repo (workspaces)
      - name: Install deps
        run: npm ci --workspaces --include-workspace-root

      # Build both workspaces; your root package.json orchestrates this
      - name: Build (frontend + backend)
        run: npm run build

      # Make sure the UI ends up under the backend's public dir
      - name: Move UI into backend public
        run: mkdir -p backend/dist/public && cp -r frontend/dist/* backend/dist/public/

      # Zip backend only for faster deploys
      - name: Package backend
        run: |
          cd backend
          zip -r ../backend.zip .

      - name: Deploy to Azure Web App (prod)
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'docsearchengine-amd3dvf7hch0cnax'   # <-- your real app name
          package: 'backend.zip'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISH_PROFILE }}
